<a href="https://colab.research.google.com/github/abhishekmali9191/Java/blob/main/DataAnalytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##** Day1 -----     09/10/2024   **

In [ ]:
# Data Analytics
import numpy as np

my_list = [1,2,3]
my_array = np.array([1,2,3])

print(type(my_array))
print(type(my_list))

#Creating a numpy array from a list
print(np.array(my_list))

# or from a list of list
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(np.array(my_matrix))

#Creating array using built in function
#Return evenly spaced values within a given interval
#start, stop, step
print(np.arange(0,10))
print(np.arange(0,11,2))    # print in space of 2

#generating arrays of zeros and ones
print(np.zeros(3))
print(np.zeros((5,5)))
print(np.ones(3))
print(np.ones((3,3)))

#return evenly spaced numbers over a specified interval
# start , stop, number of elements (and not step )
#unlike numpy.arrange(), the stop value is included in the result
#the spacing between values is automatically determined based on the specified number of values(num)
print(np.linspace(0,10,3))
print(np.linspace(0,5,20))
print(np.linspace(0,5,21))


#Random number array
print(np.random.rand(2))
print(np.random.rand(5,5))


#From normal distribution
print(np.random.randn(2))
print(np.random.randn(5,5))

#Random integers from low( inclusive ) to high (exclusive)
print(np.random.randint(1,100))  # Single random integers between 1 and 100
print(np.random.randint(1,100,10))  # 10 random integers between 1 and 100

#Seeding for reproducable result
np.random.seed(77)
print(np.random.rand(4))    # 4 random numbers    #but for all machines will get the same random numbers

#sorting
arr = np.arange(25) # number from 0 to 24
ranarr = np.random.randint(0,50,10)    # 10 random numbers bwetween 0 and 50
print(arr)
print(ranarr)

#reshape : Return an array containing the same data with in new shape
print(arr.reshape(5,5))

#Max, min and their index position
print(ranarr.max())
print(ranarr.argmax())
print(ranarr.min())
print(ranarr.argmin())


<class 'numpy.ndarray'>
<class 'list'>
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]
[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0.  5. 10.]
[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]
[0.52464842 0.63843832]
[[0.00284013 0.65130106 0.98898687 0.81828873 0.24360658]
 [0.22812317 0.76785962 0.20260465 0.13234272 0.21045074]
 [0.71167998 0.88415092 0.33309666 0.69399463 0.68207569]
 [0.90892432 0.53015323 0.3889611  0.80376068 0.65543829]
 [0.38245402 0.22696156 0.40525894 0.91393039 0.06201439]]
[-0.86821705 -1.33807076]
[[-0.77295851 -0.57535269  1.5293654  -0.3647

In [ ]:
import numpy as np

#Creating sample array
arr = np.arange(0,11)
print(arr)

#bracket indexing and selection - similar to python list
#get value at an index
print(arr[8])

#Get values in a range
print(arr[1:8])

#Broadcasting
#Setting a value with index range (Broadcasting)
arr[0:5]=100
print(arr)

#Important notes on slices
slice_of_arr = arr[0:6]
print(slice_of_arr)

#Change slice
slice_of_arr[:]=99
print(slice_of_arr)
print(arr)
#Changes made are also there in our original array!
#Data is not copies, it is a view of the original array
#This avoid a memory problem

#To get a copy, we need to be explicit
arr_copy = arr.copy()
print(arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10]
8
[1 2 3 4 5 6 7]
[100 100 100 100 100   5   6   7   8   9  10]
[100 100 100 100 100   5]
[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]
[99 99 99 99 99 99  6  7  8  9 10]


In [ ]:
#Conditional selection
arr = np.arange(1,10)
print(arr)

#Basic Arithmetic
print(arr + arr)
print(arr - arr)
print(arr * arr)

#This will raise a Warining on division by Zero , but not an error!
# It just fills the spot with nan
print(arr/arr)

# Also a warning (but not an error) relating to infifnity
print(1/arr)

print(arr**3)

# Universal functions
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

# summary statistics
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.var())
print(arr.std())


[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0]
[ 1  4  9 16 25 36 49 64 81]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111]
[  1   8  27  64 125 216 343 512 729]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
45
5.0
9
1
6.666666666666667
2.581988897471611


In [ ]:
#2 D array
#This is a 2-dimentional array with 3 rows and 4 cloumns
arr_2D = np.array([[1,2,3,8],[4,5,6,7],[9,8,7,6]])
print(arr_2D)

#Row and column count
print(arr_2D.shape)
#Sum all the columns for each row
print(arr_2D.sum(axis=0))
#Sum all the rows for each cloumns
print(arr_2D.sum(axis=1))

In [ ]:
#Assignment 1
import numpy as np

# 1. Create an array of 10 zeros
array_of_zeros = np.zeros(10)
print("1. Array of 10 zeros:", array_of_zeros)

# 2. Create an array of 10 ones
array_of_ones = np.ones(10)
print("2. Array of 10 ones:", array_of_ones)

# 3. Create an array of 10 fives
array_of_fives = np.full(10, 5)
print("3. Array of 10 fives:", array_of_fives)

# 4. Create an array of the integers from 10 to 50
array_of_integers = np.arange(10, 51)
print("4. Array of integers from 10 to 50:", array_of_integers)

# 5. Create an array of all the even integers from 10 to 50
even_integers = np.arange(10, 51, 2)
print("5. Array of even integers from 10 to 50:", even_integers)

# 6. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("6. 3x3 matrix with values from 0 to 8:\n", matrix_3x3)

# 7. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("7. 3x3 identity matrix:\n", identity_matrix)

# 8. Use NumPy to generate a random number between 0 and 1
random_number = np.random.rand()
print("8. Random number between 0 and 1:", random_number)

# 9. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
random_array = np.random.randn(25)
print("9. Array of 25 random numbers from standard normal distribution:\n", random_array)

# 10. Create an array of 20 linearly spaced points between 0 and 1
linearly_spaced = np.linspace(0, 1, 20)
print("10. Array of 20 linearly spaced points between 0 and 1:", linearly_spaced)

1. Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2. Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
3. Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]
4. Array of integers from 10 to 50: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
5. Array of even integers from 10 to 50: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
6. 3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
7. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
8. Random number between 0 and 1: 0.08731954798960007
9. Array of 25 random numbers from standard normal distribution:
 [-0.65064811  1.07787751 -1.58344033  0.25033584 -2.24306114  1.02454513
  0.79793928  0.51000977 -1.65211862  0.71711855  0.9772284  -1.04084922
 -0.64351952 -0.11251978 -0.31416646  1.6274397  -0.36122727 -0.17304574
 -1.95130924 -0.97821016  0.15815505 -1.17837853 -0.51555091 -0.06301549
 -0.55937093]
10. Array of 20 linearly 

#Day 2 ------ 10/10/2024-------|

In [1]:
import numpy as np

In [141]:
# Numpy assignment DA Lab

#1 Write a NumPy program to get the numpy version and show numpy build configuration.

print(np.version)
print(np.show_config)
print("-"*50)

#2 Write a NumPy program to get help on the add function.
# print(np.info(np.add))
print("-"*50)


#3 Write a NumPy program to test whether none of the elements of a given array is zero.
arr = np.random.randint(0,20,5)
print(arr)
print(arr==0)
arrbool=arr<7
print(arrbool)
arr[arrbool]

#4 Write a NumPy program to test whether any of the elements of a given array is non-zero.
arr = np.random.randint(0,20,6)
print(arr)
arrBool = arr!=0
arrBool

#5 Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).
arr = np.random.randint(0,100,10)
print('Infintiy check')
print(arr)
arrbool=arr==np.inf
print(arrbool)
arr=np.array([np.inf,0,np.NaN,23,56])
print(arr)
print(np.isinf(arr))
#7 Write a NumPy program to test element-wise for NaN of a given array.
print('Non value check')
print(np.isnan(arr))
print("-"*50)

#6Write a NumPy program to test element-wise for positive or negative infinity.
print('Infinity check')
arr=np.array([np.inf,0,np.NaN,23,56,-np.inf,-5])
print(arr)
print(np.isinf(arr))
print("-"*50)

# #8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also
# test whether a given number is a scalar type or not.
print('Complex number check')
arr=np.array([5+4j,0,np.NaN,23+5j,56,np.inf,-5])
print(arr)
print(np.iscomplex(arr))

# #9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and
# less_equal) of two given arrays.
print("element-wise comparison")
arr1 = np.array([11,44,33,77,22,55])
arr2 = np.array([22,11,44,66,44,33])
print('greater : ',np.greater(arr1,arr2))
print('greater and equal : ',np.greater_equal(arr1,arr2))
print('Less : ',np.less(arr1,arr2))
print('Less_equal : ',np.less_equal(arr1,arr2))

#10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the
# memory occupied by the array.
print('size of the memory occupied by the array.')
arr = np.array([1, 7, 13, 105])
print(arr.nbytes)

#11. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
print('create an array of 10 zeros')
arr1 = np.zeros(10)
print(arr1)
print('create an array of 10 ones')
arr2 = np.ones(10)
print(arr2)
print('create an array of 10 ones')
arr3 = np.full(10,5)
print(arr3)

#12. Write a NumPy program to create an array of the integers from 30 to70.
print('array of the integers from 30 to70')
arr = np.arange(30,71)
print(arr)

#13. Write a NumPy program to create an array of all the even integers from 30 to 70.
print('array of the integers from 30 to70 even integer')
arr = np.arange(30,71,2)
print(arr)

#14. Write a NumPy program to create a 3x3 identity matrix.
print('3x3 identity matrix')
identity_matrix = np.eye(3)
print(identity_matrix)

#15. Write a NumPy program to generate a random number between 0 and 1.
print('Random array between 0 and 1')
arr = np.random.rand(3)
print(arr)

# 16. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
random_array = np.random.randn(15)
print("9. Array of 25 random numbers from standard normal distribution:\n", random_array)


#17. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
# except the first and last.
print('15 to 55 and print all values except the first and last')
arr = np.arange(15,56)
print(arr[1:-1])

#18 Write a NumPy program to create a 3X4 array.
print('3X4 array')
arr2D = np.array([[1,2,3,4],[5,6,7,8],[9,7,6,5]])
arr2D
arr2 = np.random.randint(0,100,12).reshape(3,4)
arr2

#19. Write a NumPy program to create a vector of length 10 with values evenly distributed
# between 5 and 50.
print('5 - 50 range even array of 10 elements')
arr = np.arange(5,51,5)
print(arr)
arr1 = np.linspace(5,50,10)
print(arr1)

# 20. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the
# numbers in the range from 9 to 15.
print('0 to 20 and change the sign of the numbers in the range from 9 to 15')
arr = np.arange(0,21)
arr[9:16]= -arr[9:16]
print(arr)

# 21. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
arr = np.random.randint(0,11,5)
print(arr)

#22. Write a NumPy program to multiply the values of two given vectors.
print('array multiplication')
arr1 = np.array([1,2,3,4,5])
print(arr1*arr1)

#23. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
print('3x4 matrix filled with values from 10 to 21')
arr2 = np.random.randint(10,21,12).reshape(3,4)
print(arr2)

#24. Write a NumPy program to find the number of rows and columns of a given matrix.
print('Dimension of array')
arr2D = np.array([[1,2,3,4],[5,6,7,8],[9,7,6,5]])
print(arr2D.shape)

#25. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.
print('identity matrix')
arr = np.eye(3)
print(arr)

#26. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be
# equal to 1, and inside 0.
print(' 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.')
arrZero = np.ones((10,10))
arrZero[1:-1, 1:-1] =0
print(arrZero)

#27. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
# 3, 4, 5.
print('5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.')
arr = np.diag([1,2,3,4,5])
print(arr)

#28. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
print('3x3x3 array filled with arbitrary values')
arr = np.random.randint(0,27,27).reshape(3,3,3)
print(arr)

#29. Write a NumPy program to compute the inner product of two given vectors.
print('Dot product of two vectors')
arr1 = np.array([11,22,33])
arr2 = np.array([1,2,3])
print(np.dot(arr1,arr2))

#30. Write a NumPy program to sort a given array by row and column in ascending order.
print('array sorting')
arr2D = np.array([[1,4,2,3],[9,7,2,5],[5,7,6,8]])
print(np.sort(np.sort(arr2D,axis=0), axis=1))

#31. Write a NumPy program to extract all numbers from a given array which are less and greater
# than a specified number.
print('given array which are less and greater')
arr = np.array([1,2,3,4,5,5,6,5,7,8,8,4,9])
print(arr[arr> 5])
print(arr[arr< 5])


#32. Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a
# given number.
print('given array which are equal less and greater')
arr = np.array([1,2,3,4,5,5,6,5,7,8,8,4,9])
print(arr[arr> 5])
print(arr[arr< 5])
print(arr[arr==5])


#33. Write a NumPy program to create an array of equal shape and data type of a given array.
print('array of equal shape and data type of a given array')
arr = np.random.randint(0, 9, 5)
print(arr)
arr1 = np.empty_like(arr)
print(arr1)

#34. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.
print('3D array 1')
arr3D = np.random.randint(0,61,60).reshape(3,4,5)
print(arr3D)

#35. Write a NumPy program to multiply two given arrays of same size element-by-element.
print('array multiplication')
arr1 = np.array([1,2,3,4,5])
print(arr1*arr1)
arr2D = np.array([[1,2,3,4],[5,6,7,8],[9,7,6,5]])
print(arr2D * arr2D)

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>
<function show at 0x790eccba2560>
--------------------------------------------------
--------------------------------------------------
[ 5  6  9  5 17]
[False False False False False]
[ True  True False  True False]
[15  1 17 13  5 13]
Infintiy check
[97 32 84 56 52 49 42 30  1 90]
[False False False False False False False False False False]
[inf  0. nan 23. 56.]
[ True False False False False]
Non value check
[False False  True False False]
--------------------------------------------------
Infinity check
[ inf   0.  nan  23.  56. -inf  -5.]
[ True False False False False  True False]
--------------------------------------------------
Complex number check
[ 5.+4.j  0.+0.j nan+0.j 23.+5.j 56.+0.j inf+0.j -5.+0.j]
[ True False False  True False False False]
element-wise comparison
greater :  [False  True False  True False  True]
greater and equal :  [False  True False  True False  True]
Less :  [ 